server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inference?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8


logging:
  level:
    com.zm.inference: debug
#  file:
#    path: "D:/Projects/Log/inference/test.log"

mybatis:
  mapper-locations: classpath:com/zm/inference/mapper/*Mapper.xml
  type-aliases-package: com.zm.inference
  configuration:
    map-underscore-to-camel-case: true